spring.application.name=movie

## Server Port Setting
server.port = 81

## H2 DB Setting
spring.h2.console.enabled = true
spring.h2.console.path = /h2

## DB Setting
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

## schema.sql ??? ????? ??, ?????? ?? ? DB? ???? ???? ????
spring.sql.init.schema-locations = classpath:db/h2/schema.sql
spring.sql.init.data-locations = classpath:db/h2/data.sql
spring.jpa.hibernate.ddl-auto = none
spring.sql.init.mode=always

## ETC
spring.jpa.defer-datasource-initialization = true
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG