-- 서버 실행시 해당 스키마를 자동으로 실행시켜줌

CREATE TABLE IF NOT EXISTS MEMBER_TEST (
    MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);

-- 영화 테이블 생성
CREATE TABLE IF NOT EXISTS MOVIE (
    MOVIE_CD VARCHAR(255) PRIMARY KEY, -- 영화코드(고유코드)
    MOVIE_NM VARCHAR(255) NOT NULL, -- 영화이름
    OPEN_DT DATE NOT NULL, -- 영화 개봉일
    SHOW_TIME INTEGER NOT NULL  -- 상영시간
);

-- 영화사 테이블 생성
CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_CD VARCHAR(255) PRIMARY KEY , -- 회사코드
    COMPANY_NM VARCHAR(255) NOT NULL -- 회사이름
);

-- 영화인 테이블 생성(감독, 배우 등)
CREATE TABLE IF NOT EXISTS PEOPLE (
    PEOPLE_CD VARCHAR(255) PRIMARY KEY,  -- 영화인 코드
    PEOPLE_NM VARCHAR(255) NOT NULL, -- 영화인 이름
    BIRTHDAY DATE,
    GENDER CHAR(1)
);

-- 영화에 출현한 영화인 테이불 생성
CREATE TABLE IF NOT EXISTS MOVIE_PEOPLE (
    PEOPLE_CD VARCHAR(255),  -- 영화인 코드
    MOVIE_CD VARCHAR(255), -- 영화 코드
    ROLE VARCHAR(255), -- 영화인 역할
    PRIMARY KEY (PEOPLE_CD, MOVIE_CD, ROLE),
    FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD),
    FOREIGN KEY (PEOPLE_CD) REFERENCES PEOPLE(PEOPLE_CD)
);

-- 영화를 제작한 영화사 테이블 생성
CREATE TABLE IF NOT EXISTS MOVIE_COMPANY (
    COMPANY_CD VARCHAR(255) , -- 회사코드
    MOVIE_CD VARCHAR(255),
    PRIMARY KEY (COMPANY_CD, MOVIE_CD),
    FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD),
    FOREIGN KEY (COMPANY_CD) REFERENCES COMPANY(COMPANY_CD)
);

-- 일별박스오피스 테이블 생성
CREATE TABLE IF NOT EXISTS DAILY_BOX_OFFICE (
    DAILYBOXOFFICE_ID INTEGER AUTO_INCREMENT PRIMARY KEY ,
    MOVIE_CD VARCHAR(255) NOT NULL,
    TARGET_DT DATE,
    RANK INTEGER,
    AUDIENCE BIGINT,
    SALES BIGINT,
    FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD)
);

-- 주간박스오피스 테이블 생성
CREATE TABLE IF NOT EXISTS WEEKLY_BOX_OFFICE (
     WEEKLYBOXOFFICE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
     MOVIE_CD VARCHAR(255) NOT NULL,
     WEEK_GB VARCHAR(255) NOT NULL, -- 주간/주말/주중 선택: “0” : 주간 (월~일), “1” : 주말 (금~일) (default), “2” : 주중 (월~목)
     TARGET_DT DATE,
     RANK INTEGER,
     AUDIENCE BIGINT,
     SALES BIGINT,
     FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD)
);

