-- 서버 실행시 해당 스키마를 자동으로 실행시켜줌

CREATE TABLE IF NOT EXISTS MEMBER_TEST (
    MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);