-- 서버 실행시 해당 스키마를 자동으로 실행시켜줌

CREATE TABLE IF NOT EXISTS MEMBER_TEST (
    MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICK_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);

-- 영화 테이블 생성
CREATE TABLE IF NOT EXISTS MOVIE (
    MOVIE_CD VARCHAR(255) PRIMARY KEY, -- 영화코드(고유코드)
    MOVIE_NM VARCHAR(255) NOT NULL, -- 영화이름
    OPEN_DT DATE NOT NULL -- 영화 개봉일
);

-- 영화사 테이블 생성
CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_CD VARCHAR(255) PRIMARY KEY , -- 회사코드
    COMPANY_NM VARCHAR(255) NOT NULL -- 회사이름
);

-- 영화사상세정보 테이블 생성
CREATE TABLE IF NOT EXISTS COMPANY_DETAIL (
    COMPANY_CD VARCHAR(255) PRIMARY KEY , -- 영화코드(고유코드)
    CEO_NM VARCHAR(255) NOT NULL,
    FOREIGN KEY (COMPANY_CD) REFERENCES COMPANY(COMPANY_CD)
);

-- 영화인 목록 테이블 생성(감독, 배우 등)
CREATE TABLE IF NOT EXISTS PEOPLE_LIST (
    PEOPLE_CD VARCHAR(255) PRIMARY KEY,  -- 영화인 코드
    PEOPLE_NM VARCHAR(255) NOT NULL, -- 영화인 이름
    PEOPLE_ROLE VARCHAR(255) NOT NULL -- 영화인 역할
);

-- 영화상세정보 테이블 생성
CREATE TABLE IF NOT EXISTS MOVIE_DETAIL (
    MOVIE_CD VARCHAR(255) PRIMARY KEY , -- 영화코드(고유코드)
    SHOW_TIME INTEGER NOT NULL,  -- 상영시간
    PEOPLE_CD VARCHAR(255) NOT NULL,
    FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD),
    FOREIGN KEY (PEOPLE_CD) REFERENCES PEOPLE_LIST(PEOPLE_CD)
);

-- 영화인상세정보 테이블 생성
CREATE TABLE IF NOT EXISTS PEOPLE_DETAIL (
    PEOPLE_CD VARCHAR(255) PRIMARY KEY , -- 영화인코드(고유코드)
    BIRTHDAY DATE NOT NULL,
    FOREIGN KEY (PEOPLE_CD) REFERENCES PEOPLE_LIST(PEOPLE_CD)
);

-- 일별박스오피스 테이블 생성
CREATE TABLE IF NOT EXISTS DAILY_BOX_OFFICE (
    DAILYBOXOFFICE_ID INTEGER AUTO_INCREMENT PRIMARY KEY ,
    MOVIE_CD VARCHAR(255) NOT NULL,
    TARGET_DT DATE NOT NULL,
    FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD)
);

-- 주간박스오피스 테이블 생성
CREATE TABLE IF NOT EXISTS WEEKLY_BOX_OFFICE (
     WEEKLYBOXOFFICE_ID INTEGER AUTO_INCREMENT PRIMARY KEY ,
     MOVIE_CD VARCHAR(255) NOT NULL,
     TARGET_DT DATE NOT NULL,
     WEEKGB VARCHAR(255) NOT NULL, -- 주간/주말/주중 선택: “0” : 주간 (월~일), “1” : 주말 (금~일) (default), “2” : 주중 (월~목)
     FOREIGN KEY (MOVIE_CD) REFERENCES MOVIE(MOVIE_CD)
);

